### ISSUE TITLE
Warn about OAS spec too long

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-oas-checker#2]
## Reproduce

When an OAS spec is too long or complex

## I expect

the webapp to:
- ask for confirmation before validating
- disable the onChange validation feature
- show a progressbar
- suggest using the `spectral` cli

## Instead

The webapp start the validation
which may take minutes

**Comment by ioggstream** [comment]
@sebbalex which is the best way to warn the user before validating a very long specification file, eg. something more `modern` than an `alert` dialog?

**Comment by sebbalex** [comment]
@ioggstream Bootstrap Italia provide a simple component which act as you suppose, see [here](https://italia.github.io/bootstrap-italia/docs/componenti/alert/)
