### ISSUE TITLE
Readme in english.

### ISSUE THREAD

**Issue by ioggstream** [teamdigitale/api-oas-checker#21]
##  I expect

A readme.md in English

**Comment by peppelinux** [comment]
Yes, It's really needed!
Today I'm moving to have a fully compliant OAS3 schema from django-rest-framework, here's the Issue:
https://github.com/encode/django-rest-framework/issues/7452

It would be better to show to a wider audience an English Readme.

**Comment by ioggstream** [comment]
Ciao @peppelinux, feel free to PR :P
